#!/usr/bin/perl -w
#----------------------------------------------------------------------
# Clam Antivirus virus scanner filesystem scanning.
#
# copyright (C) 2004 Shad L. Lords <slords@mail.com>
# Copyright (C) 2005 Gordon Rowell <gordonr@gormand.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License or more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

use strict;
use esmith::ConfigDB;

my $db = esmith::ConfigDB->open_ro or die "Couldn't open ConfigDB";

my $filesystems = $db->get_prop("clamscan", "FilesystemScanFilesystems") || '/';

my $MailReport = $db->get_prop("clamscan", "FilesystemScanReportTo") || 'root';

my $clamscan_opts = " --recursive --infected --stdout" .
		    " --log /var/log/clamav/clamscan.log";

my $clamscan_opts = " --max-files=10000 --max-filesize=30MB " .
		    " --max-scansize=100MB --max-recursion=16 --max-dir-recursion=15";

my $quarantine_dir = $db->get_prop("clamscan", "QuarantineDirectory") ||
		"/var/spool/clamav/quarantine";

my @exclude = split /,/, ($db->get_prop("clamscan", "FilesystemScanExclude") ||
			  "/proc,/sys,/usr/share/doc");

push @exclude, $quarantine_dir;

$clamscan_opts .= " --exclude=$_" for (@exclude);

$clamscan_opts .= " --move=$quarantine_dir"
if ($db->get_prop("clamscan", "Quarantine") || "disabled") eq "enabled";

$clamscan_opts .= " --official-db-only=yes"
        if ($db->get_prop("clamscan", "FilesystemScanUnofficialSigs") || 'disabled') ne "enabled";

## use Bytecode
## http://blog.clamav.net/2014/11/brief-re-introduction-to-clamav.html
$clamscan_opts .= " --bytecode=yes"
        if ($db->get_prop("clamscan", "Bytecode") || 'enabled') eq "enabled";

if (($db->get_prop("clamscan", "Bytecode") || 'enabled') eq "enabled") {
	my $bytecodetimeout = $db->get_prop("clamscan", "BytecodeTimout") ||
		"120000";
	$clamscan_opts .= " --bytecode-timeout=$bytecodetimeout";

$clamscan_opts .= " --bytecode-unsigned=yes"
        if ($db->get_prop("clamscan", "BytecodeUnsigned") || 'disabled') eq "enabled";
}

## detect PUA
##see complete list at http://www.clamav.net/documents/potentially-unwanted-applications-pua

$clamscan_opts .= " --detect-pua=yes"
        if ($db->get_prop("clamscan", "DetectPua") || 'disabled') eq "enabled";

my @puaexclude = split /,/, ($db->get_prop("clamscan", "ExcludePua") || '');

if (($db->get_prop("clamscan", "DetectPua") || 'disabled') eq "enabled") {
$clamscan_opts .= " --exclude-pua=$_" for (@puaexclude)
}

###  Scanning
$clamscan_opts .= " --scan-html=yes"
      if ($db->get_prop("clamscan", "ScanHTML") || "enabled") eq "enabled";

$clamscan_opts .= " --scan-mail=yes"
        if ($db->get_prop("clamscan", "ScanMail") || "enabled") eq "enabled";

$clamscan_opts .= " --scan-archive=yes"
        if ($db->get_prop("clamscan", "ScanArchive") || "enabled") eq "enabled";

$clamscan_opts .= " --scan-pdf=yes"
        if ($db->get_prop("clamscan", "ScanPdf") || "enabled") eq "enabled";

$clamscan_opts .= " --scan-ole2=yes"
        if ($db->get_prop("clamscan", "ScanOle2") || "enabled") eq "enabled";

$clamscan_opts .= " --scan-elf=yes"
        if ($db->get_prop("clamscan", "ScanElf") || "enabled") eq "enabled";

$clamscan_opts .= " --scan-pe=yes"
        if ($db->get_prop("clamscan", "ScanPe") || "enabled") eq "enabled";

$clamscan_opts .= " --detect-broken=yes"
        if ($db->get_prop("clamscan", "DetectBroken") || "disabled") eq "enabled";

$clamscan_opts .= " --block-encrypted=yes"
        if ($db->get_prop("clamscan", "BlockEncrypted") || "disabled") eq "enabled";

#launch clamscan and email the rapport
open CLAMSCAN, "-|", "nice /usr/bin/clamscan $clamscan_opts $filesystems 2> /var/log/clamav/clamscan-errors.log";

my @report = <CLAMSCAN>;
close CLAMSCAN;

my $hostname = $db->get_value("SystemName") . "." .
	$db->get_value("DomainName");

my $date = localtime;

open MAIL, "| /bin/mail " .
	"-s \"[$hostname] Clam Antivirus Scan Results - $date\" $MailReport";

print MAIL @report;
close MAIL;
