#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-clamscan-update';
    event_actions($event,
'initialize-default-databases' => '00');
#templates to do
templates2events('/etc/cron.d/clamscan', $event);

$event = 'nethserver-clamscan-save';
#templates to do
templates2events('/etc/cron.d/clamscan', $event);

$event = 'nethserver-clamscan-restore';
event_actions($event,
'nethserver-clamscan-restore' => '10');

$event = 'nethserver-clamscan-restore-and-exclude';
event_actions($event,
'nethserver-clamscan-restore' => '10');

$event = 'nethserver-clamscan-restore-all';
event_actions($event,
'nethserver-clamscan-restore' => '10');

$event = 'freshclam-update';
event_actions($event,
'nethserver-clamscan-freshclam-update' => '10');

$event = 'nethserver-clamscan-now';
event_actions($event,
'nethserver-clamscan-now' => '10');
templates2events('/etc/cron.d/clamscan', $event);
