#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-clamscan-update';
    event_actions($event,
'initialize-default-databases' => '00');
#templates to do
templates2events('/etc/cron.d/clamscan', $event);
templates2events('/etc/sudoers', $event);

my $event = 'nethserver-clamscan-save';
#templates to do
templates2events('/etc/cron.d/clamscan', $event);
templates2events('/etc/sudoers', $event);
