#!/usr/bin/perl
use esmith::ConfigDB;
use esmith::DB;
use File::Copy;

my $db = esmith::ConfigDB->open() || die 'cannot open configuration database';
my $q = esmith::ConfigDB->open('quarantine') || die 'cannot open quarantine database';
my $restore = $db->get_prop('clamscan','restore') || '';
my $restoreall = $db->get_prop('clamscan','restoreAll') || 'disabled';

if ($restoreall eq 'enabled') {
    foreach my $resto ($q->get_all_by_prop(type => 'quarantined')) {
    my $pathresto= $resto->key;
    my $pathquarantine = $q->get_prop($pathresto,'quarantine');
    move("$pathquarantine","$pathresto");
    $q->get($pathresto)->delete;
    $db->get('clamscan')->delete_prop('restoreAll');
    }
}

exit 0 unless $restore;

my @restore = split(',',$restore);
foreach my $resto (@restore) {
my $pathquarantine = $q->get_prop($resto,'quarantine');
move("$pathquarantine","$resto");
$db->get('clamscan')->delete_prop('restore');
$q->get($resto)->delete;
}
